/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrowJNIAdapter */

#ifndef _Included_ArrowJNIAdapter
#define _Included_ArrowJNIAdapter
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_ArrowJNIAdapter_Convert2CdataInterface
  (JNIEnv *, jclass, jobject);


#ifdef __cplusplus
}
#endif
#endif
