FROM openjdk:11

RUN apt-get update \
    && apt-get install -y time

COPY logging.xml /root
COPY flight-server-all.jar /root/
COPY run_relay_server.sh /root/
COPY alloc.wasm /root
COPY filter.wasm /root

CMD ["/root/run_relay_server.sh", "arrow-flight", "80"]