FROM openjdk:11

RUN apt-get update \
    && apt-get install -y time

COPY logging.xml /root
COPY flight-server-all.jar /root/
COPY run_both_servers.sh /root/

CMD ["/root/run_both_servers.sh", "false"]
